### ISSUE TITLE
INSTRUMENT_ERROR, Instrument is disabled for trading

### ISSUE THREAD

**Issue by CooleRnax** [Fatal1ty/tinkoff-api#4]
When I try to buy on Instrument BBG000000000
I get an error that Instrument is disabled for trading.
Please help!

Here is how I generate but order
```
    await rest.orders.create_limit_order(
        figi="BBG000000000",
        lots=size,
        price=price_bid,
        operation=OperationType.BUY,
    )
```

Traceback 
```
Traceback (most recent call last):
  File "D:\Dropbox\Dev\Trading\Market Maker\Tinkoff\Bot.py", line 265, in <module>
    main()
  File "D:\Dropbox\Dev\Trading\Market Maker\Tinkoff\Bot.py", line 261, in main
    loop.run_until_complete(logic())
  File "C:\ProgramData\Anaconda3\lib\asyncio\base_events.py", line 467, in run_until_complete
    return future.result()
  File "D:\Dropbox\Dev\Trading\Market Maker\Tinkoff\Bot.py", line 246, in logic
    await buy(s, price_bid, positions, currencies)
  File "D:\Dropbox\Dev\Trading\Market Maker\Tinkoff\Bot.py", line 223, in buy
    operation=OperationType.BUY,
  File "C:\ProgramData\Anaconda3\lib\site-packages\tinkoff\investments\api\orders.py", line 55, in create_limit_order
    price=price,
  File "C:\ProgramData\Anaconda3\lib\site-packages\tinkoff\investments\api\base.py", line 29, in _request
    code=response.payload.get('code'),
tinkoff.investments.client.exceptions.TinkoffInvestmentsAPIError: INSTRUMENT_ERROR, Instrument is disabled for trading
```

**Comment by Fatal1ty** [comment]
The error is pretty clear. This instrument was temporarily or permanently unavailable for trading. Did you try to buy it at the time when it was possible to buy it using an official app?

**Comment by CooleRnax** [comment]
Instrument is available via official app, this error happed during trade hours.

**Comment by Fatal1ty** [comment]
I guess this specific instrument "Вечный портфель USD" is really disabled for trading for some reason. I recommend asking about it here https://github.com/TinkoffCreditSystems/invest-openapi
